# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ceroflux
email: finn@ceroflux.com
description: >- # this means to ignore newlines until "baseurl:"
  Almost everything is possible in games and software and it's our goal to try and reach new limits! Whether it's for entertainment or more serious purposes, we are always ready for the next challenge.
baseurl: ""
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
excerpt_separator: <!--content-->

# Build settings
markdown: kramdown